### ISSUE TITLE
Camera_info is incorrectly published for Format7 image frames

### ISSUE THREAD

**Issue by Lenskiy** [ros-drivers/camera1394#36]
There  is a problem in the way camera1394 package publishes camera_info. It adds non zero ROI parameters, however it publishes already cropped image. OpenCV tries to crop ROI from the already cropped image.

```
$ ROS_NAMESPACE=stereo_sync rosrun stereo_image_proc stereo_image_proc

OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp, line 323
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp, line 323
libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
terminating with uncaught exception of type cv::Exception: /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
```

Originally the issue was posted here 
https://github.com/ros-perception/image_pipeline/issues/55#issuecomment-42770636

**Comment by boblob** [comment]
I'm having this same problem. I have a Point Grey Firefly MV MTC and calibrated in Format7_Mode1 (cropped to 640x480, then binned to 320x240).  Launch file:
```
<launch>

  <!-- Firefly MTC Stereo (Format7-Mode1 320x240 @ 120 Hz)-->
  <group ns="stereo" >

    <!-- left camera -->
    <node pkg="camera1394" type="camera1394_node" name="left_node" output="screen">
      <param name="guid" value="00b09d0100a01a9a" />
      <param name="use_ros_time" value="True" />
      <param name="video_mode" value="format7_mode1" />

      <!-- ROI width/height in UNBINNED pixels -->
      <param name="roi_width" value="640" />
      <param name="roi_height" value="480" />

      <!-- ROI x/y offset in UNBINNED pixels -->
      <param name="x_offset" value="56" />
      <param name="y_offset" value="0" />

      <param name="camera_info_url" 
      	     value="file://$(find simple_stereo)/cfg/2015.01.19_stereo_firefly_mtc_ros_320x240_left.yml"/>
      <remap from="camera" to="left" />
    </node>
...
  </group>
</launch>
```

I calibrated with this setting which produced the following YAML file:
```
image_width: 320
image_height: 240
camera_name: narrow_stereo/left
camera_matrix:
  rows: 3
  cols: 3
  data: [186.684368, 0, 185.178204, 0, 185.935135, 113.514201, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.280265, 0.086241, -3.2e-05, -0.000334, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [0.999979, -0.000403, -0.006536999999999999, 0.000398, 1, -0.000672, 0.006536999999999999, 0.00067, 0.9999779999999999]
projection_matrix:
  rows: 3
  cols: 4
  data: [174.012789, 0, 172.847595, 0, 0, 174.012789, 111.874925, 0, 0, 0, 1, 0]
``` 

Launching the driver with that calibration gives the following CameraInfo:
```
height: 240
width: 320
distortion_model: ''
D: []
K: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
binning_x: 2
binning_y: 2
roi: 
  x_offset: 56
  y_offset: 0
  height: 480
  width: 640
  do_rectify: False
```

The parameters do not get filled in and the following warning is produced:
```
[ WARN] [1421775566.996886679]: Calibrated image size (320x240) matches neither full Format7 size (752x480)) nor ROI size (640x480)
```

Reading [REP-0104](http://www.ros.org/reps/rep-0104.html#use-cases), it seems like one is only supposed to calibrate with the full size image and any cropping or binning should be noted (i.e. we should not pretend that the above camera is actually 320x240). Is that correct/documented anywhere?
